services:
  - type: web
    name: astrografia-api
    env: docker
    plan: free
    region: oregon  # ou frankfurt, se preferir menor latência na Europa
    rootDir: backend
    dockerfilePath: Dockerfile
