services:
  - type: web
    name: astrografia-api
    env: python
    plan: free
    region: oregon  # ou frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
