services:
  backend:
    container_name: astrografia_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/app/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/app/ephe:/app/ephe
    restart: unless-stopped
