version: "3.9"  # Boa prática: defina explicitamente a versão do Compose

services:
  backend:
    container_name: astrografia_backend
    build:
      context: ./backend             # Diretório onde está o Dockerfile e o app
      dockerfile: Dockerfile         # Nome do Dockerfile dentro da pasta backend
    ports:
      - "5000:5000"                  # Mapeia porta local:container
    env_file:
      - ./backend/.env              # Variáveis de ambiente carregadas
    environment:
      - PYTHONPATH=/app             # Importante para permitir imports relativos
    volumes:
      - ./backend/ephe:/app/ephe    # Persistência de efemérides
    restart: unless-stopped         # Reinício automático, exceto se parar manualmente
