# netlify.toml — Astrografia 🌌 (2025-04-30)
# -----------------------------------------------
# Configurações de Build e Functions
# Site:      arquivos estáticos em /src
# Functions: serverless em /netlify/functions
# API proxy: amigável com /api/*

[build]
  publish   = "src"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Suporte a import/export modernos
  included_files = ["utils/**"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
