# netlify.toml — Astrografia 🌌 (2025-04-30)
# ------------------------------------------
# Configuração de build, API e funções serverless

[build]
  # Diretório onde estão os arquivos do site estático (index.html, assets etc.)
  publish   = "src"

  # Diretório onde estão suas funções serverless (como generateMap.js)
  functions = "netlify/functions"

[functions]
  # Usa esbuild como empacotador (moderno, rápido, suporta import/export e require)
  node_bundler = "esbuild"

  # Garante que arquivos auxiliares usados por funções (como /utils) sejam incluídos no build
  included_files = [
    "utils/**",             # Inclui arquivos utilitários compartilhados
    "netlify/functions/**"  # Inclui dependências entre funções (caso uma use a outra)
  ]

[[redirects]]
  # Redireciona todas as chamadas para /api/* para /.netlify/functions/*
  # Ex: /api/generateMap → /.netlify/functions/generateMap
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
