# netlify.toml — Astrografia 🌌
# ----------------------------------------
# Configuração de build e funções serverless

[build]
  publish   = "src"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/**",
    "node_modules/astronomia/data/**"
  ]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
