# netlify.toml — Astrografia 🌌
# ----------------------------------------
# Configuração de build e funções serverless

[build]
  publish   = "src"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
