# netlify.toml — Astrografia 🌌 (2025-04-30)
# ----------------------------------------------------
# Configuração de build, API e funções serverless

[build]
  publish   = "src"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Suporte a import/export e require modernos
  included_files = [
    "utils/**",             # Inclui utilitários externos às funções
    "netlify/functions/**"  # Garante que dependências locais entre funções sejam inclusas
  ]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true
