name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
      working-directory: .

    - name: Run tests with coverage
      run: |
        # Define PYTHONPATH para incluir o diretório raiz onde src está
        export PYTHONPATH=.
        # Executa pytest com coverage, falhando se abaixo de 90%
        pytest --cov=src --cov-report=term-missing --cov-fail-under=90
      working-directory: ./backend

