version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # Carrega variáveis do arquivo .env
    volumes:
      # Monta o código local no contêiner para desenvolvimento (opcional)
      # - ./backend:/app
      # Garante que os arquivos de efemérides estejam presentes
      - ./backend/ephe:/app/ephe 
    # Define um nome para o contêiner (opcional)
    container_name: astrografia_backend
    # Reinicia automaticamente em caso de falha (opcional, bom para produção)
    # restart: unless-stopped 

# Redes (opcional, útil se houver mais serviços como DB)
# networks:
#   astrografia_net:
#     driver: bridge

# Volumes (opcional, útil para persistência de dados de DB)
# volumes:
#   db_data:

