name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🐍 Configura Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: ✅ Executa testes com cobertura (se houver)
        working-directory: backend
        run: |
          export PYTHONPATH=.
          pytest --cov=. --cov-report=term-missing --cov-fail-under=80 || echo "⚠️ Testes não encontrados ou cobertura insuficiente"
