name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1) Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node.js e cache de dependências
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3) Instalação limpa de dependências
      - name: Install dependencies
        run: npm ci

      # 4) Linter
      - name: Lint code
        run: npm run lint

      # 5) Testes
      - name: Run tests
        run: npm test

      # 6) Instala Netlify CLI (se ainda não estiver em devDependencies)
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # 7) Build via Netlify CLI
      - name: Build static assets via Netlify CLI
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:   ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify build --context production
