name: Netlify Deploy

on:
  push:
    branches: [main]         # produção
  pull_request:              # preview em cada PR
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (opcional) instale dependências e rode build se precisar
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: npm
      # - run: npm ci
      # - run: npm run build   # se seu netlify.toml exige

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          # Ajuste se publish-dir for diferente
          publish-dir: ./src
          functions-dir: ./netlify/functions
          production-deploy: ${{ github.event_name == 'push' }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
          alias:              ${{ github.head_ref || 'main' }}-preview
        env:
          # Passa vars de ambiente, se necessário
          NODE_VERSION: '20'
